#--
# Copyright 2013 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#++

require 'rubygems'
require 'pathname'
require 'yaml'
require_relative 'lib/constants'
$stdout.sync = true
$stderr.sync = true

namespace :openshift do
  task :install_deps do
    spec_files = []
    parent_dir = Pathname.new(File.expand_path("__FILE__/../../"))
    Vagrant::Openshift::Constants.repos.each do |name, url|
      repo_dir = parent_dir + name
      spec_files += Dir.glob((repo_dir + "**/*.spec").to_s)
    end

    all_build_dependencies = []
    all_inst_dependencies  = []
    spec_files.each do |spec|
      spec_build_deps = YAML.load(`./yum-listbuilddep #{spec}`)
      all_build_dependencies += spec_build_deps

      spec_inst_deps = `rpm -q --specfile --requires #{spec}`.split("\n")
      all_inst_dependencies += spec_inst_deps
    end

    all_packages = all_build_dependencies + all_inst_dependencies
    print "Installing #{all_packages.size} in chunks of 20 packages"
    all_packages.uniq.each_slice(20) do |list|
      system %{sudo yum install -y --skip-broken "#{list.join('" "')}"}
    end
  end


end
